### PR TITLE
Use markdownit instead

### PR DESCRIPTION
**Pull request by lambdalisue**
To support the followings, use [markdown-it][] instead of [marked][].

* [CommonMark](http://commonmark.org/)
* [PHP markdown extra style abbreviation](https://github.com/markdown-it/markdown-it-abbr)
* [Pandoc style definition list](https://github.com/markdown-it/markdown-it-deflist)
* [Pandoc style footnote](https://github.com/markdown-it/markdown-it-footnote)
* [Pandoc style subscript](https://github.com/markdown-it/markdown-it-sub)
* [Pandoc style superscript](https://github.com/markdown-it/markdown-it-sup)

[markdown-it]: https://github.com/markdown-it/markdown-it
[marked]: https://github.com/chjj/marked

<details>
<summary>Example markdown</summary>

``````markdown
# PHP markdown extra style abbreviation
*[HTML]: Hyper Text Markup Language
*[W3C]:  World Wide Web Consortium
The HTML specification
is maintained by the W3C.

# Pandoc style definition list
Term 1

:   Definition 1

Term 2 with *inline markup*

:   Definition 2

        { some code, part of Definition 2 }

    Third paragraph of definition 2.

# Pandoc style footnote
Here is a footnote reference,[^1] and another.[^longnote]

[^1]: Here is the footnote.

[^longnote]: Here's one with multiple blocks.

    Subsequent paragraphs are indented to show that they
belong to the previous footnote.

# Pandoc style subscript
H~2~O

# Pandoc style superscript
29^th^

# GFM style table

| Option | Description |
| ------ | ----------- |
| data   | path to data files to supply the data that will be passed into templates. |
| engine | engine to be used for processing templates. Handlebars is the default. |
| ext    | extension to be used for dest files. |

Right aligned columns

| Option | Description |
| ------:| -----------:|
| data   | path to data files to supply the data that will be passed into templates. |
| engine | engine to be used for processing templates. Handlebars is the default. |
| ext    | extension to be used for dest files. |

# Code block

```html
<body>
    <p>Hello world</p>
</body>
```
</pre>

# Mermaid

```mermaid
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->E;
```
``````
</details>

<details>
<summary>Rendering result of above example</summary>
screen shot 2017-08-04 at 15 28 09
</details>

### CODE REVIEW

**Comment by lambdalisue** [comment]
Ah... It seems markdown-it has a bit different syntax for tabular thing.
I'll check it.

**Comment by lambdalisue** [comment]
Ok now. GFM style table and strikeout is supported as well.
https://github.com/markdown-it/markdown-it#syntax-extensions

**Comment by kannokanno** [comment]
That’s awesome!
Sorry, confirmation will be about a bit later.

Thanks.

**Comment by kannokanno** [comment]
It looks good 👍

**Pull request merged**
